{"name": "Проверка статус-кода при неверных данных для логина", "status": "passed", "steps": [{"name": "Отправка запроса", "status": "passed", "parameters": [{"name": "method", "value": "'POST'"}, {"name": "endpoint", "value": "'/auth/login'"}, {"name": "json", "value": "{'email': 'invalid_user@example.com', 'password': 'wrongpassword'}"}], "start": 1737273835861, "stop": 1737273836009}], "start": 1737273835860, "stop": 1737273836009, "uuid": "b89681cf-1fd2-44eb-8b2b-e2c480cda06b", "historyId": "f4c42de982a1ae16685628d424c975ad", "testCaseId": "f4c42de982a1ae16685628d424c975ad", "fullName": "tests.test_login_user.TestUserLogin#test_login_invalid_credentials_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}