{"name": "Проверка сообщения об ошибке при обновлении пароля пользователя без авторизации", "status": "passed", "steps": [{"name": "Отправка запроса", "status": "passed", "parameters": [{"name": "method", "value": "'PATCH'"}, {"name": "endpoint", "value": "'/auth/user'"}, {"name": "json", "value": "{'password': 'newpassword123'}"}], "start": 1737273839793, "stop": 1737273839933}], "start": 1737273839792, "stop": 1737273839933, "uuid": "1aad91bf-e511-4b43-bfab-cba2a0aef531", "historyId": "da5b3c4a1434d9b0ab76936a897577a3", "testCaseId": "da5b3c4a1434d9b0ab76936a897577a3", "fullName": "tests.test_update_user_data.TestUserUpdate#test_update_user_without_auth_password_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}