{"name": "Проверка ошибки при создании уже существующего пользователя", "status": "passed", "steps": [{"name": "Регистрируем пользователя", "status": "broken", "statusDetails": {"message": "ValueError: Failed to register user: 403, User already exists\n", "trace": "  File \"D:\\yandex\\Diplom_Sergei_Bazhenov_15\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\yandex\\Diplom_Sergei_Bazhenov_15\\Diplom_2\\methods.py\", line 23, in register_user\n    raise ValueError(f\"Failed to register user: {response.status_code}, {error_message}\")\n"}, "parameters": [{"name": "data", "value": "{'email': 'test_wzqbpiwc@example.com', 'password': 'testpass123', 'name': 'Test User'}"}], "start": 1737273831172, "stop": 1737273831314}], "attachments": [{"name": "stdout", "source": "f45167d4-9754-4100-b81f-b2041baf7aec-attachment.txt", "type": "text/plain"}], "start": 1737273831172, "stop": 1737273831344, "uuid": "d61c56ec-7e80-4e16-90d2-f84d5bb95e1c", "historyId": "37621dca6a1efad1a991bce77ad13a76", "testCaseId": "37621dca6a1efad1a991bce77ad13a76", "fullName": "tests.test_create_user.TestCreateUser#test_create_existing_user_raises_exception", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}