{"name": "Проверка наличия ключа 'orders' в ответе для авторизованного пользователя", "status": "passed", "start": 1737273833361, "stop": 1737273833807, "uuid": "c81d5ab7-1301-4159-9686-80e27494a8db", "historyId": "8d5c73f335c4c145d2b490dfdda3f9c5", "testCaseId": "8d5c73f335c4c145d2b490dfdda3f9c5", "fullName": "tests.test_get_orders.TestGetUserOrders#test_get_orders_authorized_user_key_in_response", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}